# Generated by Django 4.1.7 on 2023-04-13 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_contrato_mes', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('data', models.CharField(max_length=7)),
                ('contrato_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contrato.contrato')),
            ],
            options={
                'db_table': 'comissao',
            },
        ),
    ]
