# Generated by Django 4.1.7 on 2023-04-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comissao',
            old_name='contrato_id',
            new_name='contrato',
        ),
    ]
