# Generated by Django 4.1.7 on 2023-05-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comissao', '0002_rename_contrato_id_comissao_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='comissao',
            name='comissao_retroativa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
