# Generated by Django 4.1.7 on 2023-04-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='flinativo',
            field=models.BooleanField(default=False),
        ),
    ]
