# Generated by Django 4.1.7 on 2023-04-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoevento',
            name='evento_data',
            field=models.DateTimeField(),
        ),
    ]
